name: mariadb-build

on:
  push:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  mariadb-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}
      - name: treehouses mariadb
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          repo="jleekwong/mariadb"
          base="balenalib/raspberry-pi-debian"
          variant="debian"
          source sha_function.sh
          debian_x86_sha=$(get_variant_sha "$variant" "latest" "amd64")
          echo "$variant amd64"
          echo $debian_x86_sha
          variant_debian_x86_sha=$(get_manifest_sha "$repo:latest" "amd64")
          echo "treehouses/$variant amd64"
          echo $variant_debian_x86_sha
          balena_rpi_sha=$(get_tag_sha "$base" "latest")
          echo $balena_rpi_sha
          variant_rpi_sha=$(get_manifest_sha "$repo:latest" "arm")
          echo $variant_rpi_sha
          debian_arm64_sha=$(get_variant_sha "$variant" "latest" "arm64")
          echo $debian_arm64_sha
          variant_debian_arm64_sha=$(get_manifest_sha "$repo:latest" "arm64")
          echo $variant_debian_arm64_sha
          flag=$(compare_sha  "$debian_x86_sha" "$variant_debian_x86_sha" "$balena_rpi_sha" "$variant_rpi_sha" "$debian_arm64_sha" "$variant_debian_arm64_sha")
          echo $flag
          tag="3.12-$(date +%Y%m%d%H%M)"
          tag2="latest"
          echo $tag
          docker manifest create $repo:$tag "$variant@"$debian_x86_sha "$base@"$balena_rpi_sha "$variant@"$debian_arm64_sha
          docker manifest create $repo:latest "$variant@"$debian_x86_sha "$base@"$balena_rpi_sha "$variant@"$debian_arm64_sha
          docker manifest annotate $repo:latest "$base@"$balena_rpi_sha --arch arm
          docker manifest annotate $repo:$tag "$variant@"$debian_arm64_sha --arch arm64
          docker manifest annotate $repo:latest "$variant@"$debian_arm64_sha --arch arm64
          docker manifest annotate $repo:$tag "$base@"$balena_rpi_sha --arch arm
          docker manifest inspect $repo:$tag
          docker manifest inspect $repo:$tag2
          if [[ $flag == true ]]; then
            docker manifest push $repo:$tag; docker manifest push $repo:$tag2
          else
            echo "no changes"
          fi
